ip:                 "10.1.10.61"            # the IP addres of your norbit
cmd_port:           2209                    # the port the norbit listens for commands. normally/default 2209
bathy_port:         2210                    # the port which bathymetry is published. normally/default 2210
sensor_frame:       "norbit"                # the TF frame of the norbit
pointcloud_topic:   "cloud"                 # the topic you want to send your pointclouds on
bathymetric_topic:  "bathymetric"           # norbit_msgs raw bathymetric topic
detections_topic:   "detections"            # hydrographic_msgs detection topic

# watercolumn stuff If both are left blank WC data will not be requested from the unit
norbit_watercolumn_topic: "watercolumn_raw" # the norbit_msgs watercolum message topic.  not published if blank.
watercolumn_topic:  "watercolumn"           # the hydrographic_msgs watercolum topic.  not published if blank.
cmd_timeout:        0.5                     # how long should you wait for a command response before you consider it timed out
startup_settings:                           # the norbit settings to be applied at startup (see doc/*DFD_external.pdf)
    set_power:        "1"
    set_gate_mode:    "1"
    set_range:        ".5 30"
    set_time_source:  "1"                    # 0: IRIG-B 1:NTP 2: IRIG-B (inverted) 3: NTP+PPS(pos) 4: NTP+PPS(neg) 5: ZDA+PPS(pos) 6:ZDA+PPS(neg) 7:ZDA 8:Free run (time since startup)
    #set_ntp_server:   "timepi.aura"

shutdown_settings:
    set_power:      "0"
